### ISSUE TITLE
Javascript parameter name collision

### ISSUE THREAD

**Issue by jbauschatz** [jbauschatz/ServiceWizard#29]
It's possible for the generated angular service functions to have collisions in the parameter names. If a path parameter were named "params" or "data", that would collide with the generated parameters by those names.

I would propose throwing an error on generation that says there's a collision and generation cannot be performed. OR we could name the offending parameter "data2" or "params2" or somesuch.

**Comment by forana** [comment]
IMO print out a warning message and let it happen anyway. Renaming them would also be unexpected functionality.
