### ISSUE TITLE
General log of generation process

### ISSUE THREAD

**Issue by jbauschatz** [jbauschatz/ServiceWizard#32]
There should be some log statements going by as the generation process executes.

This would list what classes are found, what files are generated, and when the process completes successfully.

**Comment by forana** [comment]
:+1:

**Comment by jbauschatz** [comment]
@forana do you have a favorite library we might want to use? My first instinct is that we won't need one, but I know that's wrong. Hey, I'm learning.

**Comment by forana** [comment]
Left a comment in your latest PR about using http://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html

**Comment by forana** [comment]
Which I'm totally willing to tackle btw - I have strong feelings on how that should be handled.

**Comment by jbauschatz** [comment]
By all means work these feelings out.

**Comment by jbauschatz** [comment]
It better use fourteen layers of dependency injection.
