### ISSUE TITLE
"Auto-generated by ServiceWizard" watermark

### ISSUE THREAD

**Issue by jbauschatz** [jbauschatz/ServiceWizard#34]
Should we include a "watermark" on our generated code that points out the code is auto-generated?

This could be helpful for teams using our project, to keep track of what files not to edit.

**Comment by forana** [comment]
No real thoughts one way or the other on this one. For markdown or HTML, if they use a custom template, they lose that. Could be neato to have, though.

**Comment by jbauschatz** [comment]
Ok without a reason not to I'm inclined to add one.
