### ISSUE TITLE
Content type

### ISSUE THREAD

**Issue by jbauschatz** [jbauschatz/ServiceWizard#4]
For requests that have a body, content-type should be set appropriately.

Is it safe to always set this to application/json? Or should this be set based on the @Consumes annotation in the service? If so, should one javascript function be created for each content type in the @Consumes annotation?

**Comment by jbauschatz** [comment]
@forana comments appreciated :)

**Comment by forana** [comment]
Dropwizard by default returns `application/json`. This is overridable at both the resource class level and the route level via `@Consumes`. Probably want to follow that same set for rules.

**Comment by jbauschatz** [comment]
I think Angular's $http service is correctly setting the content type based on the parameters and body its given.

Should the content type be added to the markdown API doc?
