### ISSUE TITLE
Smurf typing on annotations

### ISSUE THREAD

**Issue by forana** [jbauschatz/ServiceWizard#6]
Having to type `ServiceWizard` before each and every annotation feels wrong. All of dropwizard's underlying libraries' annotations are grouped by package, but have generic names (`@Consumes`, `@Timed`, etc).

Maybe change `@ServiceWizardService` and `@ServiceWizardMethod` to something like `@Service` and `@Method`? There's at least one major conflict with that (Spring), but I feel like we can come up with a synonym for that that isn't jarring.

**Comment by jbauschatz** [comment]
Maybe a shorter name like @WizardService and @WizardMethod would read better, but I do want to avoid potential naming conflicts with Spring because fully qualified names are such an eyesore.

**Comment by forana** [comment]
here's a scandalous thought... what if it was just one annotation, `@Wizard`? Title and description are the major overlaps, but things like content-type could count as a "default" for all routes contained in that resource.

**Comment by jbauschatz** [comment]
Hmm, it's not a bad idea. I think that there won't be any content-type and such on the annotations - that should all be gathered by the framework based on existing annotations or project config. I would rather scan for Jersey's annotations than ask the user to provide (probably duplicate) content-type information in Wizard annotations.

But I do like this idea of having one annotations for classes and methods.
